go_to_checkout = '[class^="g-btn g-btn-black cart-popup__to-cart"]'
delivery_pick_point = '//*[contains(@class,"RadioMethods_optionLabel")][text()="Пункты выдачи заказов"]/..'
select_point = '[class*="Pickup_selectBtn"]'
post_code = '//*[contains(@class,"AddressForm_postcodeText")]/strong[text()="197198"]'
checkbox_email = '(//*[@class="g-checkbox-tick gri gri-tick"])[1]'
checkbox_sms = '(//*[@class="g-checkbox-tick gri gri-tick"])[2]'
checkbox_phone = '(//*[@class="g-checkbox-tick gri gri-tick"])[3]'
refresh_sub = '//*[@class="message-content"]/*[text()="Мы обновили вашу подписку."]'
courier_delivery = '//*[contains(@class,"RadioMethods_optionLabel")][text()="Курьерская доставка"]/..'
